from jose import ExpiredSignatureError, JWTError, jwt

from config.settings.jwt import JWT_SECRET_KEY, TOKEN_TYPE


def get_user_id_from_access_token(
    token: str,
    secret_key: str = JWT_SECRET_KEY,
    algorithm: str = "HS256",
    issuer: str = "https://auth.logto.io",
    audience: str = "https://all.service.io",
) -> int:
    """
    hint we have separate Jwt Service but for prevent coupling from jwt service

    use that similar Secret key
    but for production we have asymmetric secrate key
    that generated by Logto

    """
    token_type = TOKEN_TYPE
    if token_type in token.lower():
        token = token[len(token_type) :].strip()

    print("token is ", token)
    try:
        payload = jwt.decode(
            token,
            secret_key,
            algorithms=[algorithm],
            audience=audience,
            issuer=issuer,
            options={"require": ["exp", "iat", "aud", "iss", "sub", "type"]},
        )

        if payload.get("type") != "access":
            raise ValueError("Token is not an access token")

        return int(payload["sub"])

    except ExpiredSignatureError as exc:
        raise ValueError("Access token has expired") from exc
    except JWTError as exc:
        raise ValueError(f"Invalid access token {exc}") from exc
    except KeyError as exc:
        raise ValueError("Token missing required claim") from exc


def main():
    access_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MSIsImp0aSI6ImVsVExyay1pUlpjZHNldlJGd3lzTWJwMnRJRSIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3ODEyOTEzMzAuMjk2NzQ2LCJuYmYiOjE3ODEyOTEzMzAuMjk2NzQ2LCJleHAiOjE3ODEyOTIyMzAuMjk2NzQ2LCJpc3MiOiJodHRwczovL2F1dGgubG9ndG8uaW8iLCJhdWQiOiJodHRwczovL2FsbC5zZXJ2aWNlLmlvIn0.W72Yi0vnA8dTtql4VHjFg7VPNIMMx5uUdJfuh-Uq4oY"

    user_id = get_user_id_from_access_token(access_token)
    print(user_id)


if __name__ == "__main__":
    main()
