# Generated by Django 6.0.6 on 2026-06-12 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(db_index=True, max_length=30, unique=True)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=10)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='users_usera_user_id_7253a2_idx'), models.Index(fields=['username'], name='users_usera_usernam_2ee36e_idx')],
            },
        ),
    ]
