# Generated by Django 6.0.6 on 2026-06-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_admin_user_alter_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='token_hash',
            field=models.CharField(max_length=64),
        ),
    ]
