# Generated by Django 6.0.6 on 2026-06-13 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from dana.users.models import Admin
class Migration(migrations.Migration):

    dependencies = [
        ('trasnport', '0001_initial'),
        ('users', '0004_alter_userapp_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
