version: "3.9"

services:

  db:
    image: postgres:16
    container_name: postgres-django
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=dana
      - POSTGRES_USER=Dana
      - POSTGRES_PASSWORD=Dana123
    volumes:
      - postgres-data-django:/var/lib/postgresql/data/

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: 'pg_pass'
  #   ports:
  #     - "5053:80"

  # rabbitmq:
  #   image: "rabbitmq:alpine"
  #   container_name: rabbitmq
  #   healthcheck:
  #     test: rabbitmq-diagnostics -q ping
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3

  redis:
    image: redis:latest
    container_name: redis-django
    ports:
      - 6378:6378
    volumes:
      - redis-data-django:/data


volumes:
    postgres-data-django:
    redis-data-django:

